[package]
name = "web_interface"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
afire = { git = "https://github.com/Basicprogrammer10/afire.git" }